version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      wasmtime:
        patterns:
        - "wasmtime*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      upload-download-artifact:
        patterns:
        - "upload-artifact"
        - "download-artifact"
