[package]
name = "mcp-wasmtime"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tracing-subscriber = "0.3"
tracing = "0.1"
mcp-sdk = "0.0.3"
wasmtime = "29.0.1"
wasmtime-wasi = "29.0.1"
component2json = { path = "crates/component2json" }
lifecycle-manager = { path = "crates/lifecycle-manager" }

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
mcp-sdk = { workspace = true }
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
component2json = { workspace = true }
lifecycle-manager = { workspace = true }

[[bin]]
name = "mcp-wasmtime"
path = "src/main.rs"

# [[bin]]
# name = "inspect"
# path = "cmd/main.rs"

[[bin]]
name = "component2json"
path = "cmd/component2json.rs"

[workspace]
members = [
    ".",
    "crates/component2json", 
    "crates/lifecycle-manager",
]
