version: '3.8'

services:
  # API Server
  api:
    build: ./backend/api
    container_name: mcp-api
    ports:
      - "3000:3000"
    volumes:
      - ./backend/api:/app
      - ./extension/agents:/app/agents:ro
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm start
    restart: unless-stopped
    networks:
      - mcp-network

  # Nginx (HTTPS proxy + static file server)
  nginx:
    image: nginx:alpine
    container_name: mcp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/certs:/etc/nginx/certs:ro
      - ./extension/agents:/var/www/agents:ro
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
