# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wassette',
                'doc_host': 'https://2020-io.github.io',
                'git_url': 'https://github.com/2020-io/wassette',
                'lib_path': 'wassette'},
  'syms': {'wassette.core': {'wassette.core.foo': ('core.html#foo', 'wassette/core.py')}}}
