name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux targets
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: weld-mcp-server-linux-amd64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm64
            name: weld-mcp-server-linux-arm64
          # macOS targets
          - target: x86_64-apple-darwin
            os: macos-latest
            name: weld-mcp-server-darwin-amd64
          - target: aarch64-apple-darwin
            os: macos-latest
            name: weld-mcp-server-darwin-arm64
          # Windows targets
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: weld-mcp-server-windows-amd64.exe
          - target: aarch64-pc-windows-msvc
            os: windows-11-arm64
            name: weld-mcp-server-windows-arm64.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}

      - name: Add WASM target
        run: rustup target add wasm32-wasip2

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../${{ matrix.name }}.tar.gz weld-mcp-server
          cd -

      - name: Prepare binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../${{ matrix.name }}.zip weld-mcp-server.exe
          cd -
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ matrix.name }}.tar.gz
            ${{ matrix.name }}.zip

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -name "*.tar.gz" -exec cp {} release-assets/ \;
          find artifacts -name "*.zip" -exec cp {} release-assets/ \;
          ls -la release-assets/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: release-assets/*
          body: |
            ## Downloads

            ### Linux
            - [AMD64 (tar.gz)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/weld-mcp-server-linux-amd64.tar.gz)
            - [ARM64 (tar.gz)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/weld-mcp-server-linux-arm64.tar.gz)

            ### macOS (Darwin)
            - [AMD64/Intel (tar.gz)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/weld-mcp-server-darwin-amd64.tar.gz)
            - [ARM64/Apple Silicon (tar.gz)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/weld-mcp-server-darwin-arm64.tar.gz)

            ### Windows
            - [AMD64 (zip)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/weld-mcp-server-windows-amd64.exe.zip)
            - [ARM64 (zip)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/weld-mcp-server-windows-arm64.exe.zip)

            ## Installation

            ### Linux/macOS
            ```bash
            # Download and extract for your platform (example for Linux AMD64)
            curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/weld-mcp-server-linux-amd64.tar.gz | tar xz
            chmod +x weld-mcp-server
            ```

            ### Windows
            Download and extract the appropriate `.zip` file for your architecture.

            ## Usage
            ```bash
            # Start the MCP server
            ./weld-mcp-server serve --http --policy-file policy.yaml
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
