name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: ./scripts/install-protobuf.sh
      shell: bash
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt, clippy
    - run: 
        # needed to run rustfmt in nightly toolchain
        rustup toolchain install nightly --component rustfmt
    - name: Run fmt
      run: cargo +nightly fmt --all -- --check
    - name: Run Clippy
      run: cargo clippy --verbose --workspace
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v3
    - run: ./scripts/install-protobuf.sh
      shell: bash
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - run: rustup target add wasm32-wasip2
    - name: Build
      run: just build
    - name: Run tests
      run: just test
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mcp-wasmtime
        path: bin/mcp-wasmtime
  
  examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v3
    - run: ./scripts/install-protobuf.sh
      shell: bash
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - run: rustup target add wasm32-wasip2
    - name: Build
      run: just build-examples
    - name: Upload wasm
      uses: actions/upload-artifact@v4
      with:
        name: examples
        path: bin
  
  smoke-test:
    needs: [build, examples]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - name: Run server
      run: |
        chmod +x ./mcp-wasmtime
        RUST_LOG=debug ./mcp-wasmtime
      shell: bash
    - name: Run smoke test
      run: ./scripts/verify_components.sh
      shell: bash
    - name: Clean up
      if: always()
      run: pkill -f mcp-wasmtime
      shell: bash
